name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Utilise un seul runner pour coordonner les builds

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Extract version from package.json
      id: package-version
      run: |
        echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Build Windows version
      run: npm run build -- --win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Build Linux version
      run: npm run build -- --linux
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.PACKAGE_VERSION }}  # Utilise la version du package.json
        name: Down&Load v${{ env.PACKAGE_VERSION }}
        files: |
          dist/*.exe
          dist/*.AppImage
          dist/latest.yml  # Fichier de mise à jour automatique
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}