name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build -- --win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
        name: windows-artifacts
        path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run build -- --linux
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
        name: linux-artifacts
        path: dist/

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-artifacts
        path: dist/windows

    - name: Download Linux artifacts
      uses: actions/download-artifact@v3
      with:
        name: linux-artifacts
        path: dist/linux

    - name: Extract version from package.json
      id: package-version
      run: |
        echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.PACKAGE_VERSION }}
        name: Down&Load v${{ env.PACKAGE_VERSION }}
        files: |
          dist/windows/*.exe
          dist/linux/*.AppImage
          dist/linux/latest.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}